version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: olp-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # 直接在这里写死你的服务器公网 IP，Vite 打包时会自动读取
        - VITE_API_URL=http://47.99.85.173:8080
    container_name: olp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always